name: awsPanelMeter-copilot
version: 0.1.0.0
github: "iwalkedalongthewalllikaeninjaa/awsPanelMeter"
license: BSD3
author: "Yosuke Ueda"
maintainer: "iwalkedalongthewalllikaeninjaa@gmail.com"
copyright: "2026 Yosuke Ueda"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- copilot
- copilot-c99
- copilot-core
- copilot-language
- copilot-libraries
- copilot-prettyprinter
- copilot-interpreter

library:
  source-dirs: src

executables:
  awsPanelMeter-copilot:
    main: Main.hs
    source-dirs: app
    dependencies:
    - awsPanelMeter-copilot
