resolver: lts-22.44

packages:
- .

extra-deps:
- copilot-4.4
- copilot-c99-4.4
- copilot-core-4.4
- copilot-language-4.4
- copilot-libraries-4.4
- copilot-prettyprinter-4.4
- copilot-theorem-4.4
- copilot-interpreter-4.4
- language-c99-0.2.0
- language-c99-simple-0.3.0
- language-c99-util-0.2.0
