resolver: lts-14.27

packages:
- .

extra-deps:
- ivory-0.1.0.9
- monadLib-3.10.1
- th-abstraction-0.2.11.0
- ivory-artifact-0.1.0.5
- ivory-backend-c-0.1.0.8
- ivory-eval-0.1.0.6
- ivory-hw-0.1.0.6
- ivory-opts-0.1.0.6
- ivory-quickcheck-0.2.0.5
- ivory-serialize-0.1.0.6
- ivory-stdlib-0.1.0.5
